package bts

var _headerTemplate = `
// Code generated by kit bts. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated cache proxy package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
	{{if .EnableBatch }}"sync"{{end}}
	{{.ImportPackage}}
	{{if .EnableBatch }}"github.com/tianping526/kit/sync/errgroup"{{end}}
	{{if .UseRedis }}"github.com/redis/go-redis/v9"{{end}}
	{{if .EnableSingleFlight}}	"golang.org/x/sync/singleflight" {{end}}
)

{{if .UseBTS}}
var _ _bts
{{end }}
{{if .EnableSingleFlight}}
var cacheSingleFlights = [SFCOUNT]*singleflight.Group{SFINIT} 
{{end }}
`
