package rc

var _headerTemplate = `
// Code generated by kit rc. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated rc cache package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
	{{if .UseStrConv}}"strconv"{{end}}
	{{if .EnableBatch }}"sync"{{end}}
	{{.ImportPackage}}
	{{if .UseRedis }}"github.com/redis/go-redis/v9"{{end}}
	{{if .EnableBatch }}"github.com/tianping526/kit/sync/errgroup"{{end}}
)

var _ _rc
`
