name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        go: [ 1.22.x ]
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/go.sum"

      - name: Build
        run: make build

      - name: Test
        run: make test-coverage
